# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: draft_generators 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "draft_generators"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Raghu Betina"]
  s.date = "2018-01-24"
  s.description = "This is a set of generators that help beginners learn to program. Primarily, they generate code that is more explicit and verbose and less idiomatic and \u{201c}magical\u{201d} than the built-in scaffold generator, which is helpful for beginners while they are learning how exactly things are wired together."
  s.email = "raghu@firstdraft.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "draft_generators.gemspec",
    "lib/draft_generators.rb",
    "lib/generators/draft/layout/USAGE",
    "lib/generators/draft/layout/layout_generator.rb",
    "lib/generators/draft/layout/templates/_bootstrapcdn_assets.html.erb",
    "lib/generators/draft/layout/templates/_flashes.html.erb",
    "lib/generators/draft/layout/templates/_footer.html.erb",
    "lib/generators/draft/layout/templates/_navbar.html.erb",
    "lib/generators/draft/layout/templates/layout.html.erb",
    "lib/generators/draft/model/USAGE",
    "lib/generators/draft/model/model_generator.rb",
    "lib/generators/draft/resource/USAGE",
    "lib/generators/draft/resource/resource_generator.rb",
    "lib/generators/draft/resource/templates/controllers/controller.rb",
    "lib/generators/draft/resource/templates/controllers/read_only_controller.rb",
    "lib/generators/draft/resource/templates/specs/crud_spec.rb",
    "lib/generators/draft/resource/templates/specs/factories.rb",
    "lib/generators/draft/resource/templates/views/create_row.html.erb",
    "lib/generators/draft/resource/templates/views/destroy_row.html.erb",
    "lib/generators/draft/resource/templates/views/edit_form.html.erb",
    "lib/generators/draft/resource/templates/views/index.html.erb",
    "lib/generators/draft/resource/templates/views/new_form.html.erb",
    "lib/generators/draft/resource/templates/views/show.html.erb",
    "lib/generators/draft/resource/templates/views/update_row.html.erb"
  ]
  s.homepage = "http://github.com/raghubetina/draft_generators"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Generators that help beginners learn to program."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

